<a href="https://colab.research.google.com/github/manaf2808/BGP_ML/blob/main/BalancedData(LR_NB_SVM).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import math
import time
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import LinearSVC, SVC

# **Load Data**

In [ ]:
df = pd.read_csv('/content/Slammer.csv')

new_column_names = ['Hour+Min', 'Hour', 'Min', 'Sec','1.Number of announcements', '2.Number of withdrawals', '3.Number of announced NLRI prefixes', '4.Number of withdrawn NLRI prefixes', '5.Average AS-path length', '6.Maximum AS-path length', '7.Average unique AS-path length', '8.Number of duplicate announcements', '9.Number of implicit withdrawals', '10.Number of duplicate withdrawals', '11.Maximum edit distance', '12Iter-Arrival rate','13.Maximum edit distance = 7', '14.Maximum edit distance = 8', '15.Maximum edit distance = 9', '16.Maximum edit distance = 10', '17.Maximum edit distance = 11', '18.Maximum edit distance = 12', '19.Maximum edit distance = 13', '20.Maximum edit distance = 14', '21.Maximum edit distance = 15', '22.Maximum edit distance = 16', '23.Maximum edit distance = 17','24.Maximum AS-path length = 7', '25.Maximum AS-path length = 8', '26.Maximum AS-path length = 9', '27.Maximum AS-path length = 10', '28.Maximum AS-path length = 11', '29.Maximum AS-path length = 12', '30.Maximum AS-path length = 13', '31.Maximum AS-path length = 14', '32.Maximum AS-path length = 15', '33.Maximum AS-path length = 16', '34.Number of (IGP) packets', '35.Number of (EGP) packets','36.Number of incomplete packets', '37.Packet size (B)', 'labels']
df.columns = new_column_names

df_post = df[df['labels']==1]
n = df_post.shape[0]
print(n)

X = df.drop(df.columns[:4].tolist() + ['labels'], axis=1)
y = df['labels'].values


869


In [ ]:
positive_count = sum(y == 1)
negative_count = sum(y == -1)

print("Positive instances:", positive_count)
print("Negative instances:", negative_count)

Positive instances: 869
Negative instances: 6330


In [ ]:
df_neg = df[df['labels']==-1]
print(df_neg.shape[0])
# Randomly sample n observations from the dataframe
sample_data = df_neg.sample(n)

6330


In [ ]:
combined_df = pd.concat([df_post, sample_data], ignore_index=True)
X = combined_df.drop('labels', axis=1)
y = combined_df['labels']

In [ ]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

positive_count = sum(y_train == 1)
negative_count = sum(y_train == -1)

print("Positive instances:", positive_count)
print("Negative instances:", negative_count)

Positive instances: 684
Negative instances: 706


# **Logistic Regression**

In [ ]:
# Create an LogisticRegression classifier
classifier = LogisticRegression()

start_time = time.time()
# Train the classifier using the training data
classifier.fit(X_train, y_train)
training_time = time.time() - start_time

# Make predictions on the testing data
y_pred = classifier.predict(X_test)

# Evaluate the accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Obtain the confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

#Classification report
classification_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(classification_report)
print("Training Time:", training_time, "seconds")

Accuracy: 0.9166666666666666
Confusion Matrix:
[[146  17]
 [ 12 173]]
Classification Report:
              precision    recall  f1-score   support

          -1       0.92      0.90      0.91       163
           1       0.91      0.94      0.92       185

    accuracy                           0.92       348
   macro avg       0.92      0.92      0.92       348
weighted avg       0.92      0.92      0.92       348

Training Time: 0.0674738883972168 seconds


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


# **Naive Bayes**

In [ ]:
from sklearn.metrics import classification_report
# Create an NB classifier
classifier = GaussianNB()


start_time = time.time()
# Train the classifier using the training data
classifier.fit(X_train, y_train)
training_time = time.time() - start_time

# Make predictions on the testing data
y_pred = classifier.predict(X_test)

# Evaluate the accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Obtain the confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

#Classification report
classification_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(classification_report)

print("Training Time:", training_time, "seconds")

Accuracy: 0.8505747126436781
Confusion Matrix:
[[143  20]
 [ 32 153]]
Classification Report:
              precision    recall  f1-score   support

          -1       0.82      0.88      0.85       163
           1       0.88      0.83      0.85       185

    accuracy                           0.85       348
   macro avg       0.85      0.85      0.85       348
weighted avg       0.85      0.85      0.85       348

Training Time: 0.010294914245605469 seconds


# **SVM Different Kernels**

In [ ]:
from sklearn.metrics import classification_report
# Define the kernel functions to test
kernel_functions = ['linear', 'poly', 'rbf', 'sigmoid']

# Test different kernel functions
for kernel in kernel_functions:
    # Train the SVM model and measure the time taken
    start_time = time.time()
    svm_model = SVC(kernel=kernel)
    svm_model.fit(X_train, y_train)
    end_time = time.time()

    # Make predictions on the test data
    y_pred = svm_model.predict(X_test)

    # Print the classification report and confusion matrix
    print("Kernel Function: ", kernel)
    print(classification_report(y_test, y_pred))
    report = classification_report(y_test, y_pred, output_dict=True)
    for label, metrics in report.items():
        if label.isdigit():
            for metric, value in metrics.items():
                if metric != 'support':
                    print(f"{metric.capitalize()} ({label}): {value:.2%}")
    print(confusion_matrix(y_test, y_pred))
    accuracy = accuracy_score(y_test, y_pred)
    print("Accuracy: {:.2%}".format(accuracy))
    print("Time taken to train: {:.2f} seconds\n".format(end_time - start_time))

Kernel Function:  linear
              precision    recall  f1-score   support

          -1       0.95      0.90      0.92       163
           1       0.91      0.96      0.94       185

    accuracy                           0.93       348
   macro avg       0.93      0.93      0.93       348
weighted avg       0.93      0.93      0.93       348

Precision (1): 91.28%
Recall (1): 96.22%
F1-score (1): 93.68%
[[146  17]
 [  7 178]]
Accuracy: 93.10%
Time taken to train: 38.40 seconds

Kernel Function:  poly
              precision    recall  f1-score   support

          -1       0.92      0.90      0.91       163
           1       0.91      0.93      0.92       185

    accuracy                           0.92       348
   macro avg       0.92      0.92      0.92       348
weighted avg       0.92      0.92      0.92       348

Precision (1): 91.49%
Recall (1): 92.97%
F1-score (1): 92.23%
[[147  16]
 [ 13 172]]
Accuracy: 91.67%
Time taken to train: 0.04 seconds

Kernel Function:  rbf
 